name: PMs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: dotnet build PMs.sqlproj
      
    - name: Deploy
      run: |
        & sqlpackage /Action:Publish /SourceFile:bin/Debug/PMs.dacpac /TargetConnectionString:${{ secrets.SQL_CONNECTION_STRING }}