name: PMs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: dotnet build PMs.sqlproj

    - name: Deploy
      uses: azure/sql-action@v2
      with:
        connection-string:  ${{ secrets.SQL_CONNECTION_STRING }}
        action: 'publish'
        path: 'bin/Debug/PMs.dacpac'
