name: PMs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: dotnet build PMs.sqlproj
      
    - name: Extract Archive
      run: |
        $ErrorActionPreference = 'Stop'; 
        try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { }; 
        if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { 
            Expand-Archive -LiteralPath 'C:\path\to\your\archive.zip' -DestinationPath 'C:\path\to\destination' -Force 
        } else {
            [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\path\to\your\archive.zip', 'C:\path\to\destination', $true)
        }

    - name: Deploy
      uses: azure/sql-action@v2
      with:
        connection-string:  ${{ secrets.SQL_CONNECTION_STRING }}
        action: 'publish'
        path: 'bin/Debug/PMs.dacpac'
